---
# tasks file for roles/install-apache
- name: install apache
  yum: 
    name: httpd
    state: latest

- name: enabled apache
  service: 
    name: httpd
    enabled: true

- name: start apache
  service:
    name: httpd
    state: started
