---
# tasks file for roles/deploy-postgres
- name: install postgres
  yum:
    name: postgresql-server
    state: latest

#- name: initilize postgres
#  command: postgresql-setup initdb
#  args:
#    creates: /var/lib/pgsql/initdb.log
- name: initilize postgres
  command: postgresql-setup initdb
  register: r_postgres_initdb
  failed_when:
    - r_postgres_initdb.rc != 0
    - r_postgres_initdb.stdout != 'Data directory is not empty!'
  changed_when:
    - r_postgres_initdb.rc == 0

- name: enable postgress
  service:
    name: postgresql
    enabled: true
